gsb_visiteur_homepage:
    path:     /
    defaults: { _controller: GsbVisiteurBundle:Default:index }
    
sucesslogin:
    path: /login
    defaults: {_controller: GsbVisiteurBundle:Affichage:index}
    
login:
    path: /a
    defaults: {_controller: GsbVisiteurBundle:Connection:afficher}
    
renseigner:
    path: /renseigner
    defaults: {_controller: GsbVisiteurBundle:Renseigner:button}

consulter:    
    path: /consulter
    defaults: {_controller: GsbVisiteurBundle:Consulter:button}