gsb_visiteur:
    resource: "@GsbVisiteurBundle/Resources/config/routing.yml"
    prefix:   /


gsb_comptable:
    resource: "@GsbComptableBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
