<?php

namespace Gsb\ComptableBundle\Repository;
use Gsb\ComptableBundle\Entity\Fichefrais;
use Gsb\ComptableBundle\Entity\Lignefraisforfait;
use Gsb\ComptableBundle\Entity\Lignefraishorsforfait;
use Gsb\ComptableBundle\Entity\Etat;
use Gsb\ComptableBundle\Entity\Visiteur;
use Gsb\ComptableBundle\Entity\FraisForfait;
/**
 * FichefraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichefraisRepository extends \Doctrine\ORM\EntityRepository
{
       public function insertFicheFrais($nbjust, $montant,$jour,$mois,$annee) {
        $em = $this->getEntityManager();// $this->getDoctrine()->getManager();      
//On creer la requete 
  /* INSERT INTO `frais_forfait` (`id`, `libelle`, `montant`) VALUES (1, 'Forfait Etape', 110.00), 
   * (2, 'Frais Kilométrique', 0.62), (3, 'Nuitée Hôtel', 80.00), 
   * (4, 'Repas Restaurant', 25.00);
*/
             $date = ""+$jour+""+$mois+""+$annee;
        
               $query = $em->createQuery(
                   'INSERT INTO `fiche_frais` 
                     (`mois`,`nbJustificatif`,`montantValide`,`dateModif`,`idEtat`) VALUES (
                     :mois,:nbjust,:montant,:date,:idetat)'
                  );
                       
                  $query->setParameter('nbjust', $nbjust);
                   $query->setParameter('montant' , $montant);
                     $query->setParameter('date' , $date);
                     $query->setParameter('mois', $mois);
                     $query->setParamater('idetat',3);
                   
                   return $query->getScalarResult();

    }
    
    public function isexist($mois,$annee,$idVisiteur,$repasmidi,$nuite,$etape,$km) {
        $em = $this->getEntityManager();// $this->getDoctrine()->getManager();
       /* $repoFicheFrais = $this->getDoctrine()->getManager()->getRepository('GsbComptableBundle:Fichefrais');  
        $lefraisforfait4 = $fraisforfaitrepo ->find(4); 
        $lignefraisforfait4->setLesfraisforfait($lefraisforfait4);
        */
        
        $query = $em->createQuery(
                   'SELECT f.id
                    FROM GsbComptableBundle:fichefrais f
                    WHERE f.idVisiteur = :identifiant
                    AND f.mois = :mois
                    AND f.annee = :annee'
                  );
                    $query->setParameter('identifiant', $idVisiteur);
                    $query->setParameter('mois' , $mois);
                    $query->setParameter('annee' , $annee);
                    
                    $nbLigne = $query->getScalarResult();
                    $intrequete = (int)$nbLigne;
                    
                    var_dump("Identifiant de la fiche recherche di TROUVE " .$intrequete);
            //$fichefrais = new \Gsb\ComptableBundle\Entity\Fichefrais
        
               
                    
                    if (count($nbLigne) == 1 ) {  //si on recupere un identifiant on met a jour les données
                        
                        
                        //MISE A JOUR  des lignes frais forfait
                        
                        //ATTENTION les noms des colonnes correspondent a ceux de l'entité 
                        //pas à la base de données
                        
                            $query = $em->createQuery(
                            'UPDATE GsbComptableBundle:Lignefraisforfait l
                            SET l.quantite = :quantite
                            WHERE l.idFicheFrais = :fiche    
                            AND l.lesfraisforfait  = :numligne'
                            );
                             $query->setParameter('quantite', $etape);
                             $query->setParameter('fiche' , $intrequete);
                             $query->setParameter('numligne' , 1);
                        
                             $query->execute();
                             
                             var_dump($query->execute());
                             
                            $query2 = $em->createQuery(
                            'UPDATE GsbComptableBundle:Lignefraisforfait l
                            SET l.quantite = :quantite
                            WHERE l.idFicheFrais = :fiche
                            AND l.lesfraisforfait  = :numligne'
                            );
                             $query2->setParameter('quantite', $km);
                             $query2->setParameter('fiche' , $intrequete);
                             $query2->setParameter('numligne' , 2);
                            
                             $query2->execute();
                             
                             $query3 = $em->createQuery(
                            'UPDATE GsbComptableBundle:Lignefraisforfait l
                            SET l.quantite = :quantite
                            WHERE l.idFicheFrais = :fiche
                            AND l.lesfraisforfait  = :numligne'
                            );
                             $query3->setParameter('quantite', $nuite);
                             $query3->setParameter('fiche' , $intrequete);
                             $query3->setParameter('numligne' , 3);
                             
                             $query3->execute();
                             
                             $query4 = $em->createQuery(
                            'UPDATE GsbComptableBundle:Lignefraisforfait l
                            SET l.quantite = :quantite
                            WHERE l.idFicheFrais = :fiche
                            AND l.lesfraisforfait  = :numligne'
                            );
                             $query4->setParameter('quantite', $repasmidi);
                             $query4->setParameter('fiche' , $intrequete);
                             $query4->setParameter('numligne' , 4);
                             
                             $query4->execute();
                             
                            return TRUE;
                    
                    }
                    
                    return FALSE;
    
    
    }
    
    
    
    public function findFiche($mois,$annee,$idVisiteur) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                   'SELECT e.libelle,f.dateModif
                    FROM GsbComptableBundle:FicheFrais f
                    JOIN GsbComptableBundle:Etat e
                    WITH f.idEtat=e.id
                    WHERE f.idVisiteur = :identifiant
                    AND f.mois = :mois
                    AND f.annee=:annee'
                  );
                       
                   $query->setParameter('identifiant', $idVisiteur);
                   $query->setParameter('mois' , $mois);
                   $query->setParameter('annee' , $annee);
                   
                   $requetefiche=$query->execute();
                  
                    
                    return $requetefiche;
    }
    public function findidFiche($mois,$annee,$idVisiteur) {
        
       // $test = (string)$idVisiteur;
        var_dump('Trouver l identifiant de la fiche ' . $mois . ' ' . $annee . ' ' .$idVisiteur);
        
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                   'SELECT count(f.id)
                    FROM GsbComptableBundle:FicheFrais f
                    WHERE f.idVisiteur = :identifiant
                    AND f.mois = :mois
                    AND f.annee=:annee'
                  );
                       
                   $query->setParameter('identifiant', $idVisiteur);
                   $query->setParameter('mois' , $mois);
                   $query->setParameter('annee' , $annee);
                   
                   $requeteexist=$query->getSingleScalarResult();
                   
               $intrequetefiche = 0;
                   
              if($requeteexist != 0){
                  $query = $em->createQuery(
                   'SELECT f.id
                    FROM GsbComptableBundle:FicheFrais f
                    WHERE f.idVisiteur = :identifiant
                    AND f.mois = :mois
                    AND f.annee=:annee'
                  );
                       
                   $query->setParameter('identifiant', $idVisiteur);
                   $query->setParameter('mois' , '04');
                   $query->setParameter('annee' , $annee);
                   
                   $requetefiche=$query->getSingleScalarResult();  
                   $intrequetefiche = (int)$requetefiche;
                   
                   
                   //recuperation de la fiche sous forme d objet inutilisé ici
                  //  $repofiche = $this->getDoctrine()->getManager()->getRepository('GsbComptableBundle:Fichefrais');
                   // $return = $repofiche->find($intrequetefiche);
                   
              }     
                   
                 
                    return $intrequetefiche;
    }
}
