<?php

namespace Gsb\ComptableBundle\Repository;

/**
 * FichefraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichefraisRepository extends \Doctrine\ORM\EntityRepository
{
       public function insertFicheFrais($nbjust, $montant,$jour,$mois,$annee) {
        $em = $this->getEntityManager();// $this->getDoctrine()->getManager();      
//On creer la requete 
  /* INSERT INTO `frais_forfait` (`id`, `libelle`, `montant`) VALUES (1, 'Forfait Etape', 110.00), 
   * (2, 'Frais Kilométrique', 0.62), (3, 'Nuitée Hôtel', 80.00), 
   * (4, 'Repas Restaurant', 25.00);
*/
             $date = ""+$jour+""+$mois+""+$annee;
        
               $query = $em->createQuery(
                   'INSERT INTO `fiche_frais` 
                     (`mois`,`nbJustificatif`,`montantValide`,`dateModif`,`idEtat`) VALUES (
                     :mois,:nbjust,:montant,:date,:idetat)'
                  );
                       
                  $query->setParameter('nbjust', $nbjust);
                   $query->setParameter('montant' , $montant);
                     $query->setParameter('date' , $date);
                     $query->setParameter('mois', $mois);
                     $query->setParamater('idetat',3);
                   
                   return $query->getScalarResult();
    
    
    }
}
