<?php

namespace Gsb\ComptableBundle\Repository;

/**
 * LignefraishorsforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraishorsforfaitRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findhorsforfait($idFiche) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                   'SELECT l.libelle,l.montant,l.date
                    FROM GsbComptableBundle:Lignefraishorsforfait l
                    WHERE l.idFicheFrais = :identifiant'
                  );
                       
                   $query->setParameter('identifiant', $idFiche);
                   
                   
                   $requetehorsforfait=$query->getResult();
                       
                    /*$intrequetefiche = (int)$requetefiche;
                    $repofiche = $this->getDoctrine()->getManager()->getRepository('GsbComptableBundle:Fichefrais');
                    $return = $repofiche->find($intrequetefiche);*/
                    
                    return $requetehorsforfait;
    }
}
