<?php

namespace Gsb\ComptableBundle\Repository;

/**
 * LignefraishorsforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraishorsforfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
