<?php

namespace Gsb\ComptableBundle\Repository;

/**
 * LignefraisforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraisforfaitRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findforfait($idFiche) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                   'SELECT f.libelle,l.quantite,f.montant
                    FROM GsbComptableBundle:Lignefraisforfait l
                    JOIN GsbComptableBundle:Fraisforfait f
                    WITH l.lesfraisforfait=f.id
                    WHERE l.idFicheFrais = :identifiant'
                  );
                       
                   $query->setParameter('identifiant', $idFiche);
                   
                   
                   $requeteforfait=$query->getResult();
                       
                    /*$intrequetefiche = (int)$requetefiche;
                    $repofiche = $this->getDoctrine()->getManager()->getRepository('GsbComptableBundle:Fichefrais');
                    $return = $repofiche->find($intrequetefiche);*/
                    
                    return $requeteforfait;
    }
    
}
